"""
Protocols for object versioning.

Defines the Repo and Remote interfaces.
"""

from __future__ import annotations

from typing import Any, Dict, List, Protocol, Literal

from .models import Commit, Ref


# ----------------------------
# Repo Protocol
# ----------------------------

class Repo(Protocol):
    """Protocol for a local repository."""
    repo_id: str

    # --- states
    def put_state(self, state: List[Dict[str, Any]]) -> str: ...
    def get_state(self, state_id: str) -> List[Dict[str, Any]]: ...

    # --- commits
    def put_commit(self, commit: Commit, state_id: str) -> None: ...
    def get_commit(self, commit_id: str) -> Commit: ...
    def get_commit_state_id(self, commit_id: str) -> str: ...
    def has_commit(self, commit_id: str) -> bool: ...

    # --- refs
    def upsert_ref(self, name: str, commit_id: str, kind: Literal["branch", "tag"] = "branch") -> None: ...
    def delete_ref(self, name: str) -> None: ...
    def get_ref(self, name: str) -> Ref: ...
    def has_ref(self, name: str) -> bool: ...
    def list_refs(self) -> List[Ref]: ...

    # --- traversal
    def list_commits_first_parent(self, start_commit: str, limit: int = 50) -> List[Commit]: ...
    def list_all_commit_ids(self) -> List[str]: ...


# ----------------------------
# Remote Protocol
# ----------------------------

class Remote(Protocol):
    """A Remote is a target you can push to and pull from."""
    name: str

    def has_state(self, state_id: str) -> bool: ...
    def get_state_bytes(self, state_id: str) -> bytes: ...
    def put_state_bytes(self, state_id: str, data: bytes) -> None: ...
    def has_commit(self, commit_id: str) -> bool: ...
    def get_commit(self, commit_id: str) -> Commit: ...
    def put_commit(self, commit: Commit, state_id: str) -> None: ...
    def get_commit_state_id(self, commit_id: str) -> str: ...
    def get_ref(self, name: str) -> Ref: ...
    def has_ref(self, name: str) -> bool: ...
    def list_refs(self) -> List[Ref]: ...
    def upsert_ref(self, name: str, commit_id: str, kind: Literal["branch", "tag"] = "branch") -> None: ...
    def delete_ref(self, name: str) -> None: ...
