"""Structured catalog of experimental mechanisms in Kagel & Roth (1995).

Descriptions are concise paraphrases of the local handbook, not transcriptions.
Page references use the printed page numbers.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from html import escape
import json
from pathlib import Path


@dataclass(frozen=True)
class Game:
    slug: str
    name: str
    family: str
    chapter: int
    pages: str
    description: str
    workflow_shape: str
    status: str = "queued"
    existing_case: str | None = None
    pressure: str = ""


GAMES = (
    # Social dilemmas and coordination (chapters 1-3)
    Game("prisoners-dilemma", "Prisoner's dilemma", "Social dilemmas", 1, "26-28", "Two players privately cooperate or defect; unilateral defection is tempting although mutual cooperation dominates mutual defection.", "sealed pair choice -> matrix payoff", "implemented", "prisoners-dilemma"),
    Game("linear-public-goods", "Linear voluntary-contribution public-good game", "Social dilemmas", 2, "112-21, 134-41", "Players allocate private tokens between themselves and a group account whose return is shared, creating a free-riding incentive.", "parallel contributions -> aggregate -> repeated feedback", "implemented", "public-goods"),
    Game("threshold-public-good", "Threshold / provision-point public good", "Social dilemmas", 2, "144-48", "The public return occurs only if total contributions reach a stated threshold; variants rebate contributions when provision fails.", "parallel contributions -> threshold -> rebate/payoff", "implemented", "threshold-public-good", "Aggregate provision is implemented; participant-wise rebates remain."),
    Game("commons-dilemma", "Commons dilemma", "Social dilemmas", 2, "126-30", "Members choose whether to conserve or exploit a shared resource; individual exploitation pays privately while imposing losses on the group.", "parallel binary choice -> congestion payoff", "implemented", "commons-dilemma", "Counting, thresholding, and mapped payoffs are implemented; durable resource stock remains."),
    Game("best-shot", "Best-shot public-good game", "Social dilemmas", 4, "279-81", "The group outcome is determined by the largest individual contribution rather than their sum, making one contributor sufficient for provision.", "parallel choices -> maximum -> payoffs", "implemented", "best-shot", "Maximum and identity-preserving participant payoff mapping are implemented."),
    Game("minimum-effort", "Minimum-effort coordination game", "Coordination", 3, "209-18", "Each player chooses effort from 1 to 7; payoff rises with the group's minimum effort but falls when one's effort exceeds that minimum.", "parallel effort -> minimum -> repeated payoff feedback", "implemented", "minimum-effort", "Minimum and identity-preserving participant payoff mapping are implemented."),
    Game("median-effort", "Median-action coordination game", "Coordination", 3, "218-25", "Players choose an action and are rewarded for coordinating near a group order statistic, often under changing history or communication treatments.", "parallel choice -> median -> repeated feedback", "implemented", "median-effort", "Median, absolute distance, and participant payoff mapping are implemented."),
    Game("battle-of-sexes", "Battle of the Sexes", "Coordination", 3, "195-96, 225-33", "Two players prefer coordinating to mismatching but disagree about which coordinated outcome is best.", "sealed pair choice -> asymmetric matrix payoff", "implemented", "battle-of-sexes", "Directly expressible with payoff_matrix."),
    Game("chicken", "Chicken / hawk-dove", "Coordination", 2, "144-45", "Each player prefers standing firm when the other yields, but mutual aggression is worst for both.", "sealed pair choice -> matrix payoff", "implemented", "chicken", "Directly expressible with payoff_matrix."),
    Game("schelling-claims", "Schelling tacit claims game", "Coordination", 1, "12", "Two players independently claim shares of a fixed prize; claims are honored only when their sum does not exceed the prize.", "sealed claims -> feasibility test -> payoff", "implemented", "schelling-claims", "Fully expressible from sum, comparison, conditional, and mapped payoff."),
    Game("schelling-ranking", "Schelling tacit ranking game", "Coordination", 1, "12", "Three labeled players independently rank A, B, C; all earn rank-dependent prizes only if every ordering matches.", "parallel rankings -> all-equal -> rank payoff", "ready", "schelling-ranking", "Structured ranking equality is implemented; identity-specific rank prizes need list-position helpers."),
    Game("market-location", "Decentralized market-location coordination", "Coordination", 3, "233-44", "Players select locations with posted capacities; excess demand triggers random rationing, while exact allocation clears the market.", "changing cohorts -> location choices -> capacity lottery", pressure="Needs rematching, capacity constraints, and seeded lotteries."),

    # Bargaining (chapter 4)
    Game("unstructured-bargaining", "Unstructured bargaining", "Bargaining", 4, "255-56", "A pair negotiates a division with flexible messages until agreement or breakdown, allowing focal points and fairness norms to emerge.", "two-party conversation -> agreement/deadline", pressure="Needs conversational offers, counters, and agreement objects."),
    Game("alternating-offers", "Alternating-offer bargaining", "Bargaining", 4, "256-74", "Players alternate proposals over a shrinking or discounted pie; each response accepts or passes proposal rights to the opponent.", "bounded alternating loop -> accept or discount", pressure="Needs dynamic role swapping and a first-class agreement/termination hook."),
    Game("ultimatum", "Ultimatum game", "Bargaining", 4, "274-88, 296-302", "One player proposes a split and the responder accepts both payoffs or rejects and gives both zero.", "offer -> response -> conditional payoff", "implemented", "ultimatum"),
    Game("dictator", "Dictator game", "Bargaining", 4, "270, 298-302", "One player unilaterally chooses a transfer to a passive recipient, separating generosity from fear of rejection.", "allocation -> private payoff notices", "implemented", "dictator"),
    Game("impunity", "Impunity game", "Bargaining", 4, "300", "A responder can reject an allocation but rejection harms only the responder, leaving the allocator's payoff intact.", "offer -> response -> asymmetric conditional payoff", "implemented", "impunity", "Expressible with choose; warrants a reusable settlement object."),
    Game("optional-breakdown", "Optional-breakdown bargaining", "Bargaining", 4, "271-74", "After disagreement, either player may end bargaining for outside-option payments or continue with a discounted pie.", "alternating offers -> bilateral continue/quit -> discount", pressure="Needs joint continuation decisions and dynamic round state."),
    Game("forced-breakdown", "Probabilistic forced-breakdown bargaining", "Bargaining", 4, "271-74", "Rejected offers continue only if an exogenous probability permits; otherwise outside-option payments end the game.", "offer -> reject -> seeded hazard -> next round", pressure="Chance exists; terminal settlement across every round remains awkward."),
    Game("incomplete-info-bargaining", "Incomplete-information bargaining", "Bargaining", 4, "304-23", "Privately informed bargainers make offers that may reveal type, with delay and disagreement serving as strategic signals.", "private types -> offers/counters -> belief-sensitive settlement", pressure="Needs private scenario assignment and type-safe information policies."),
    Game("strategy-method-bargaining", "Bargaining strategy method", "Bargaining", 4, "320-23", "Participants specify responses for every possible offer before learning which contingency is realized.", "contingent response schedule -> realized branch", "ready", "dictator-strategy-method", "Serializable lookup and random contingency selection work; structured strategy-table responses remain."),
    Game("deadline-bargaining", "Deadline bargaining", "Bargaining", 4, "323-27", "Negotiation occurs under known or asymmetric deadlines, making delay and last-moment agreement strategically meaningful.", "conversation -> timers -> agreement/expiration", pressure="Needs wall-clock deadlines and race-safe late submissions."),

    # Industrial organization and trading institutions (chapter 5)
    Game("chamberlin-market", "Chamberlin decentralized market", "Market institutions", 1, "13-16", "Buyers and sellers with induced reservation values search and negotiate bilateral trades without centralized price clearing.", "repeated bilateral search -> trade -> inventory update", pressure="Needs dynamic matching, offers, inventories, and a transaction ledger."),
    Game("posted-offer", "Posted-offer market", "Market institutions", 5, "361-65", "Sellers publicly post prices and buyers choose whether and where to purchase, often with units allocated in sequence.", "seller prices -> sequential buyer choice -> trades", pressure="Needs inventories, ordering, and atomic transactions."),
    Game("posted-bid", "Posted-bid market", "Market institutions", 5, "362, 365", "Buyers post purchase prices and sellers select among them, reversing the strategic side of the posted-offer institution.", "buyer bids -> sequential seller choice -> trades", pressure="Needs inventories, ordering, and atomic transactions."),
    Game("uniform-price-market", "Uniform-price market", "Market institutions", 5, "365-66", "Multiple accepted units transact at a common clearing price determined from submitted offers or bids.", "order collection -> clearing -> uniform settlement", pressure="Needs sorting, supply-demand crossing, and multi-unit settlement."),
    Game("one-sided-sequential-auction", "One-sided sequential auction", "Market institutions", 5, "367", "Units are sold one at a time through successive auctions, allowing prices and strategies to respond to remaining supply.", "auction loop -> inventory decrement -> feedback", pressure="Needs nested market rounds and durable inventories."),
    Game("double-auction", "Continuous double auction", "Market institutions", 5, "368-72", "Buyers submit bids and sellers submit asks continuously; compatible orders transact and reveal a path of market prices.", "concurrent order stream -> matching engine -> trades", pressure="Needs event-driven order books, atomic matching, and cancellations."),
    Game("cournot", "Cournot quantity-choice oligopoly", "Industrial organization", 5, "375, 398-411", "Firms simultaneously choose quantities; market price follows aggregate output and each firm's payoff reflects its own costs.", "parallel quantities -> inverse demand -> firm payoffs", "implemented", "cournot", "Sum, parameters, and participant-wise profit mapping provide authoritative settlement."),
    Game("monopoly", "Experimental monopoly", "Industrial organization", 5, "377-83", "A single seller chooses price or quantity against induced demand, sometimes under alternative regulatory rules.", "seller decision -> demand allocation -> profit/regulation", "implemented", "monopoly", "A serialized lookup implements discrete demand and profit settlement."),
    Game("contestable-market", "Potential-entry / contestable market", "Industrial organization", 5, "383-87", "An incumbent prices while potential entrants decide whether fixed costs and post-entry competition justify entry.", "incumbent action -> entry decisions -> market payoff", "implemented", "market-entry", "Current example simplifies incumbent pricing and entry costs."),
    Game("predatory-pricing", "Predatory-pricing game", "Industrial organization", 5, "387-91", "An incumbent may sacrifice current profit to deter an entrant who is uncertain about the incumbent's type or resolve.", "private incumbent type -> entry -> pricing -> repeated beliefs", pressure="Needs private types, repetition, and belief/history views."),
    Game("oligopoly-collusion", "Repeated oligopoly / collusion", "Industrial organization", 5, "398-416", "Firms repeatedly choose prices or quantities, possibly communicate, punish deviations, or use facilitating contractual terms.", "repeated firm choices -> market payoff -> history", pressure="Repeat exists; market clearing and communication policy remain."),
    Game("lemons-quality", "Endogenous-quality lemons market", "Industrial organization", 5, "417-19, 550-57", "Privately informed sellers choose quality or offers while buyers infer value, allowing adverse selection to collapse trade or quality.", "private quality -> offer -> buyer inference -> trade", pressure="Needs private types, quality-linked values, and transactions."),
    Game("spatial-competition", "Hotelling spatial competition", "Industrial organization", 5, "419", "Firms choose locations or prices while consumers buy based on price plus travel cost.", "firm locations/prices -> consumer allocation -> profits", pressure="Needs distance calculations and market allocation."),

    # Auctions (chapter 7)
    Game("first-price-auction", "First-price sealed-bid auction", "Auctions", 7, "503-8, 514-17", "Bidders submit sealed bids; the highest bid wins and the winner pays their own bid.", "private values -> sealed bids -> argmax/payment", "implemented", "first-price-auction"),
    Game("dutch-auction", "Dutch descending-clock auction", "Auctions", 7, "503-8", "A public price clock descends until the first bidder accepts, who wins at that price.", "price clock -> first acceptance -> settlement", pressure="Needs timers, races, and atomic first-response semantics."),
    Game("second-price-auction", "Second-price / Vickrey auction", "Auctions", 7, "503-12", "The highest sealed bidder wins but pays the second-highest bid, making truthful bidding a dominant strategy in the private-value model.", "sealed bids -> top-two order statistics -> payment", "implemented", "second-price-auction", "Order statistics are implemented; deterministic tie-breaking remains."),
    Game("english-auction", "English ascending auction", "Auctions", 7, "503-12, 547-49", "A public price rises through open bids until no rival remains; the final active bidder wins at the stopping price.", "open bid loop -> exits -> last bidder", pressure="Needs live event streams, active rosters, and race-safe closure."),
    Game("third-price-auction", "Third-price sealed-bid auction", "Auctions", 7, "504, 515-17", "The highest bidder wins and pays the third-highest bid, used to probe departures from standard bidding predictions.", "sealed bids -> third order statistic -> payment", "implemented", "third-price-auction", "Order statistics are implemented; deterministic tie-breaking remains."),
    Game("common-value-auction", "Common-value sealed-bid auction", "Auctions", 7, "536-47", "All bidders ultimately value the item equally but receive noisy private signals, exposing winners to adverse selection and the winner's curse.", "latent value -> private signals -> auction -> realized profit", pressure="Needs reproducible random variables, private signals, and ex-post revelation."),
    Game("affiliated-value-auction", "Affiliated-value auction", "Auctions", 7, "517-20", "Bidder signals are correlated and informative about a common component, so public information and linkage affect bids and revenue.", "correlated private signals -> public signal -> bids", pressure="Needs declarative correlated draws and staged disclosure."),
    Game("asymmetric-auction", "Asymmetrically informed auction", "Auctions", 7, "547-50", "Some bidders possess better value information than others, changing inference and exposing poorly informed winners to losses.", "heterogeneous signals -> bids -> information-sensitive payoff", pressure="Needs role-specific private information schemas."),
    Game("blind-bid-procurement", "Blind-bid / procurement auction", "Auctions", 7, "553-57", "Sellers bid to perform a task with uncertain cost or quality; the low bidder wins and may discover that winning signals an overly optimistic estimate.", "private cost signals -> low bid -> realized cost", pressure="Needs argmin, ex-post uncertainty, and winner-only continuation."),
    Game("multiunit-auction", "Multi-unit discriminatory and uniform-price auctions", "Auctions", 5, "362-66", "Participants submit demand or supply schedules for several units; accepted units pay their own bids or a common clearing price.", "bid schedules -> rank units -> discriminatory/uniform payment", pressure="Needs structured schedules and multi-unit clearing."),

    # Asset markets (chapter 6)
    Game("information-market", "Information aggregation asset market", "Asset markets", 6, "447-64", "Traders receive dispersed private clues about an asset's state and trade claims whose prices may aggregate that information.", "private signals -> repeated orders/trades -> state payoff", pressure="Needs an order book, private signals, and terminal dividends."),
    Game("market-for-information", "Market for information", "Asset markets", 6, "461-64", "Traders can purchase information before or while trading, making information acquisition itself an endogenous decision.", "buy signal -> trade -> dividend", pressure="Needs purchasable capabilities and budget accounting."),
    Game("spot-futures", "Spot and futures market", "Asset markets", 6, "464-67", "Participants trade linked spot and state-contingent claims, permitting hedging and arbitrage across markets.", "parallel linked order books -> clearing -> contingent payoff", pressure="Needs multiple atomic markets and cross-market positions."),
    Game("asset-bubble", "Finite-horizon asset bubble market", "Asset markets", 6, "467-81", "A dividend-paying asset is repeatedly traded before a known terminal date, often producing prices above fundamental value followed by a crash.", "repeated double auction -> dividends -> terminal redemption", pressure="Needs holdings, cash, dividends, and a live matching engine."),
    Game("call-market", "Call market", "Asset markets", 6, "485-86", "Orders accumulate during a period and execute together at a clearing price, contrasting with continuous double-auction trading.", "batch orders -> clearing price -> simultaneous trades", pressure="Needs batch market clearing and rationing."),

    # Individual decision tasks (chapters 1 and 8)
    Game("probability-calibration", "Probability calibration with scoring rules", "Individual decisions", 8, "590-95", "Respondents forecast event probabilities and receive proper-score payments after outcomes are revealed.", "forecast -> outcome revelation -> proper score", "implemented", "probability-calibration", "Stable event resolution and deterministic quadratic scoring are implemented; named scoring helpers remain."),
    Game("bayesian-updating", "Bayesian updating / base-rate task", "Individual decisions", 8, "596-608", "Respondents combine priors and diagnostic evidence, testing base-rate neglect, conservatism, and representativeness.", "prior elicitation -> signal -> posterior elicitation -> score", "implemented", "bayesian-updating", "Staged signal release and deterministic Bayesian benchmark are implemented."),
    Game("curse-of-knowledge", "Curse-of-knowledge information task", "Individual decisions", 8, "612-15", "Informed participants predict judgments of less-informed participants and often fail to disregard their own information.", "baseline response -> private reveal -> prediction of baseline", "implemented", "curse-of-knowledge", "Asymmetric staged information and deterministic comparison are implemented."),
    Game("allais", "Allais common-consequence choice", "Individual decisions", 8, "619-43", "Participants make paired lottery choices designed so common-consequence behavior can violate expected-utility independence.", "paired lottery choices -> consistency classification", "implemented", "allais", "Classification is implemented; typed lotteries and incentive-compatible random selection remain."),
    Game("ellsberg", "Ellsberg ambiguity task", "Individual decisions", 8, "644-49", "Participants choose between bets with known probabilities and bets whose probability is deliberately ambiguous.", "paired known/ambiguous lottery choices -> pattern classification", "implemented", "ellsberg", "Classification is implemented; typed urns, ambiguity, and random resolution remain."),
    Game("preference-reversal", "Preference-reversal task", "Individual decisions", 8, "657-65", "Participants both choose between lotteries and price them; the preferred lottery is often assigned the lower selling price.", "choice elicitation -> valuation elicitation -> reversal test", "implemented", "preference-reversal", "Linked classification is implemented; BDM valuation and random payment selection remain."),
    Game("bdm", "Becker-DeGroot-Marschak valuation", "Individual decisions", 1, "79-80", "A participant states a reservation value, a random price is drawn, and trade occurs only when the stated value crosses that price.", "valuation -> seeded random price -> conditional trade", "implemented", "bdm-valuation", "Stable numeric draws and conditional settlement are implemented; typed money remains."),
    Game("binary-lottery", "Binary-lottery payoff procedure", "Individual decisions", 1, "81-86", "Experimental earnings determine a probability of winning a fixed prize rather than money directly, aiming to control risk preferences.", "game earnings -> probability -> prize lottery", "implemented", "binary-lottery", "Stable lottery resolution is implemented; typed lotteries remain."),
    Game("endowment-effect", "Endowment-effect exchange/valuation task", "Individual decisions", 8, "665-70", "Randomly endowed owners state willingness to accept while nonowners state willingness to pay, followed by a market or incentive-compatible trade.", "random endowment -> WTA/WTP -> trade", pressure="Needs random assignment, property ownership, and BDM/market settlement."),
    Game("intertemporal-choice", "Intertemporal choice", "Individual decisions", 8, "649-51", "Participants choose between smaller-sooner and larger-later rewards to reveal discounting and timing effects.", "dated reward choices -> delayed fulfillment", "ready", "intertemporal-choice", "Choice classification works; typed dated payments and real fulfillment remain."),
    Game("search-task", "Sequential search task", "Individual decisions", 8, "670-73", "Participants pay to sample wage, price, or information offers and decide when to stop searching and accept.", "draw offer -> accept or pay to continue -> terminal choice", "implemented", "sequential-search", "Seeded offers, conditional stopping, search costs, and lazy terminal settlement are implemented."),
)


def render(output: Path) -> Path:
    output = output.resolve()
    families = []
    for game in GAMES:
        if game.family not in families:
            families.append(game.family)
    counts = {status: sum(game.status == status for game in GAMES) for status in {g.status for g in GAMES}}
    nav = "".join(f'<a href="#{escape(f.lower().replace(" ", "-"))}">{escape(f)}</a>' for f in families)
    sections = []
    for family in families:
        cards = []
        for game in (item for item in GAMES if item.family == family):
            link = f'<a class="case" href="workflow_stress_gallery.html#{escape(game.existing_case)}">gallery case</a>' if game.existing_case else ""
            cards.append(f'''<article><div class="meta"><span class="status {game.status}">{escape(game.status)}</span><span>Chapter {game.chapter}, pp. {escape(game.pages)}</span>{link}</div><h3>{escape(game.name)}</h3><p>{escape(game.description)}</p><dl><dt>Workflow</dt><dd>{escape(game.workflow_shape)}</dd><dt>DSL pressure</dt><dd>{escape(game.pressure or "No major gap identified.")}</dd></dl></article>''')
        ident = family.lower().replace(" ", "-")
        sections.append(f'<section id="{escape(ident)}"><h2>{escape(family)}</h2><div class="grid">{"".join(cards)}</div></section>')
    payload = json.dumps([asdict(game) for game in GAMES], indent=2)
    output.write_text(f'''<!doctype html><html><head><meta charset="utf-8"><title>Handbook experimental-game catalog</title><style>html{{scroll-behavior:smooth}}body{{margin:0;background:#f2f4f7;color:#172033;font:14px/1.5 system-ui,sans-serif}}header,main{{max-width:1400px;margin:auto;padding:30px}}header{{padding-bottom:12px}}h1{{margin-bottom:6px}}header p{{max-width:900px;color:#586477}}nav{{display:flex;flex-wrap:wrap;gap:8px;margin:22px 0}}nav a,.case{{color:#5b21b6;text-decoration:none}}nav a{{padding:7px 10px;background:white;border:1px solid #d8dee8;border-radius:8px}}.summary{{display:flex;gap:12px;flex-wrap:wrap}}.summary b{{background:#172033;color:white;padding:7px 11px;border-radius:8px}}section{{scroll-margin-top:15px;margin-bottom:36px}}h2{{border-bottom:2px solid #d8dee8;padding-bottom:8px}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:14px}}article{{background:white;border:1px solid #d8dee8;border-radius:12px;padding:18px;box-shadow:0 3px 10px #1720330b}}article h3{{margin:10px 0 5px}}article p{{color:#465267;min-height:62px}}.meta{{display:flex;gap:10px;align-items:center;color:#68758a;font-size:11px}}.status{{font-weight:800;text-transform:uppercase;padding:2px 7px;border-radius:10px}}.implemented{{background:#d1fae5;color:#065f46}}.ready{{background:#dbeafe;color:#1e40af}}.queued{{background:#ede9fe;color:#5b21b6}}dl{{display:grid;grid-template-columns:82px 1fr;gap:5px 8px;margin-bottom:0}}dt{{font-weight:750;color:#68758a}}dd{{margin:0}}details{{max-width:1400px;margin:0 auto 40px;background:#111827;color:#d1d5db;padding:14px;border-radius:10px}}pre{{overflow:auto;font-size:11px}}</style></head><body><header><h1>Experimental game catalog</h1><p>{len(GAMES)} reproducible mechanism families extracted and paraphrased from <em>The Handbook of Experimental Economics</em> (Kagel &amp; Roth, 1995). Printed-page references identify the source discussion. “Implemented” links to an existing workflow; “ready” fits current primitives; “queued” exposes additional language needs.</p><div class="summary">{"".join(f"<b>{counts.get(s, 0)} {s}</b>" for s in ("implemented", "ready", "queued"))}</div><nav>{nav}</nav></header><main>{''.join(sections)}</main><details><summary>Machine-readable catalog JSON</summary><pre>{escape(payload)}</pre></details></body></html>''', encoding="utf-8")
    return output


if __name__ == "__main__":
    print(render(Path(__file__).with_suffix(".html")))
