"""A multi-round family discussion generated by real persona-driven LLM agents."""

from pathlib import Path

from edsl import Agent, AgentList, Model, QuestionFreeText, Survey
from edsl.sharedstate import FileStateStore, SharedMessageBoard, SharedState


def family_agents() -> AgentList:
    return AgentList(
        [
            Agent(
                name="John",
                traits={
                    "family_role": "parent",
                    "spouse": "Robin",
                    "children": ["Ada", "Paul"],
                    "relationships": "Robin is your spouse; Ada and Paul are your children.",
                    "preference": "Go sailing together",
                    "persona": "Practical and safety-conscious; wants the family together and seeks workable compromises.",
                },
            ),
            Agent(
                name="Robin",
                traits={
                    "family_role": "parent",
                    "spouse": "John",
                    "children": ["Ada", "Paul"],
                    "relationships": "John is your spouse; Ada and Paul are your children.",
                    "preference": "Go kayaking",
                    "persona": "Loves quiet coves and active exploration; advocates for kayaking but listens to the children.",
                },
            ),
            Agent(
                name="Ada",
                traits={
                    "family_role": "child",
                    "parents": ["John", "Robin"],
                    "sibling": "Paul",
                    "relationships": "John and Robin are your parents; Paul is your brother.",
                    "preference": "Go sailing",
                    "persona": "Enthusiastic about sailing and helping with the boat; thoughtful about everyone enjoying the day.",
                },
            ),
            Agent(
                name="Paul",
                traits={
                    "family_role": "child",
                    "parents": ["John", "Robin"],
                    "sibling": "Ada",
                    "relationships": "John and Robin are your parents; Ada is your sister.",
                    "preference": "Stay home and play video games",
                    "persona": "Would rather play games, but wants inclusion and will negotiate honestly about a family outing.",
                },
            ),
        ]
    )


def build_survey(log_path: str | Path) -> tuple[Survey, SharedState]:
    state = SharedState(
        scope="family-weekend",
        store=FileStateStore(log_path),
        board=SharedMessageBoard(),
    )
    author = QuestionFreeText(
        question_name="author",
        question_text="Return only your name. Your name is {{ agent.name }}.",
    )
    reply_to = QuestionFreeText(
        question_name="reply_to",
        question_text=(
            "Current family message board:\n{{ shared_state.board.messages }}\n\n"
            "Return only the exact author name you want to reply to, or NONE to "
            "start a new thread."
        ),
    )
    message = QuestionFreeText(
        question_name="message",
        question_text=(
            "Current family message board:\n{{ shared_state.board.messages }}\n\n"
            "Your preference: {{ agent.preference }}.\n"
            "Your persona: {{ agent.persona }}.\n"
            "Your family role: {{ agent.family_role }}.\n"
            "Your family relationships: {{ agent.relationships }}.\n"
            "You chose to reply to: {{ reply_to.answer }}.\n\n"
            "Write one concise, constructive message in your own voice. React to "
            "the discussion, advocate for your view, and seek compromise when "
            "appropriate. Do not prefix the message with your name."
        ),
    )
    survey = Survey(
        [author, reply_to, message, state.board.add(author, message, reply_to)]
    )
    return survey, state


def run_discussion(
    log_path: str | Path = "family-board.jsonl",
    rounds: int = 1,
    model_name: str = "gemini-2.5-flash",
) -> SharedState:
    """Run real LLM agents sequentially so each post sees every earlier post."""
    survey, state = build_survey(log_path)
    agents = family_agents()
    model = Model(model_name)

    for round_number in range(1, rounds + 1):
        round_agents = agents.duplicate()
        for agent in round_agents:
            agent.traits["discussion_round"] = round_number
        prior_count = state.read().state["board"]["message_count"]
        results = (
            survey.by(round_agents)
            .by(model)
            .run(
                interview_schedule="serial",
                disable_remote_inference=True,
                disable_remote_cache=True,
                cache=False,
                stop_on_exceptions=True,
            )
        )

        # The entire AgentList was submitted once. Serial scheduling preserves
        # its order, and each writing prompt contains every preceding board post.
        rows_by_name = {row["agent"]["name"]: row for row in results.to_dict()["data"]}
        messages = state.read().state["board"]["messages"]
        for offset, agent in enumerate(round_agents):
            prompt = rows_by_name[agent.name]["prompt"]["message_user_prompt"]["text"]
            visible = messages[: prior_count + offset]
            assert all(entry["message"] in prompt for entry in visible)

    return state


if __name__ == "__main__":
    board_state = run_discussion()
    print(board_state.render_markdown())
