export default function HumanPlayPage() {
  const modes = [
    {
      title: 'Human as Storyteller',
      description: 'Write your own two truths and a lie. See if the LLM judge can catch you lying.',
      icon: '✍️',
      status: 'Coming Soon',
    },
    {
      title: 'Human as Judge',
      description: 'Read stories generated by LLMs and try to identify which one is the lie.',
      icon: '🔍',
      status: 'Coming Soon',
    },
    {
      title: 'Mixed Mode',
      description: 'Compete alongside or against LLMs in multi-player rounds.',
      icon: '🎮',
      status: 'Coming Soon',
    },
  ]

  return (
    <div className="max-w-5xl mx-auto px-4 py-8">
      <div className="bg-white rounded-lg shadow p-8">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold mb-4">Human Play Mode</h2>
          <p className="text-lg text-gray-600">
            Experience the game firsthand and contribute to research
          </p>
        </div>

        <div className="grid grid-cols-3 gap-6 mb-12">
          {modes.map((mode) => (
            <div key={mode.title} className="border rounded-lg p-6 hover:shadow-lg transition-shadow">
              <div className="text-5xl mb-4 text-center">{mode.icon}</div>
              <h3 className="text-xl font-semibold mb-2 text-center">{mode.title}</h3>
              <p className="text-gray-600 text-sm mb-4 text-center">{mode.description}</p>
              <div className="text-center">
                <span className="px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-xs font-medium">
                  {mode.status}
                </span>
              </div>
            </div>
          ))}
        </div>

        {/* Interest Signup */}
        <div className="bg-gray-50 rounded-lg p-8">
          <h3 className="text-xl font-semibold mb-4 text-center">Stay Updated</h3>
          <p className="text-gray-600 mb-6 text-center">
            Human play mode is under development. Sign up to be notified when it launches.
          </p>
          <form className="max-w-md mx-auto flex space-x-2">
            <input
              type="email"
              placeholder="Enter your email"
              className="flex-1 px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
            <button
              type="submit"
              className="px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
            >
              Notify Me
            </button>
          </form>
        </div>

        {/* Research Contribution Info */}
        <div className="mt-12 border-t pt-8">
          <h3 className="text-lg font-semibold mb-4">Why Human Play Matters</h3>
          <div className="grid grid-cols-2 gap-6">
            <div className="flex items-start space-x-3">
              <span className="text-2xl">📊</span>
              <div>
                <h4 className="font-medium mb-1">Baseline Data</h4>
                <p className="text-sm text-gray-600">
                  Human performance provides crucial baseline metrics for comparing LLM capabilities.
                </p>
              </div>
            </div>
            <div className="flex items-start space-x-3">
              <span className="text-2xl">🧠</span>
              <div>
                <h4 className="font-medium mb-1">Strategy Discovery</h4>
                <p className="text-sm text-gray-600">
                  Human strategies can reveal new approaches to deception and detection.
                </p>
              </div>
            </div>
            <div className="flex items-start space-x-3">
              <span className="text-2xl">🎯</span>
              <div>
                <h4 className="font-medium mb-1">Training Data</h4>
                <p className="text-sm text-gray-600">
                  Quality human gameplay can improve future LLM training for deception tasks.
                </p>
              </div>
            </div>
            <div className="flex items-start space-x-3">
              <span className="text-2xl">🤝</span>
              <div>
                <h4 className="font-medium mb-1">Engagement</h4>
                <p className="text-sm text-gray-600">
                  Direct interaction makes the research more accessible and engaging.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
