"""Contracts and host-side resolution for probabilistic question responses."""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import math
import random
from typing import Literal, Sequence


ResolutionMethod = Literal["none", "sample", "mode"]


@dataclass(frozen=True)
class ProbabilisticResponse:
    """Configure probability elicitation and host-side answer resolution.

    The first supported representation is ``categorical``, used by multiple-choice
    questions.  Randomness is generated by EDSL after model response validation.
    """

    representation: Literal["categorical", "inclusion_probabilities"] = "categorical"
    joint_model: Literal["independent"] | None = None
    resolution: ResolutionMethod = "none"
    seed: int | None = None
    tolerance: float = 1e-6

    def __post_init__(self) -> None:
        if self.representation not in {
            "categorical",
            "inclusion_probabilities",
        }:
            raise ValueError(
                "representation must be one of: 'categorical' or "
                "'inclusion_probabilities'."
            )
        if self.joint_model not in {None, "independent"}:
            raise ValueError("joint_model must be 'independent' or None.")
        if self.representation == "categorical" and self.joint_model is not None:
            raise ValueError("categorical responses do not use a joint_model.")
        if self.representation == "inclusion_probabilities":
            if self.joint_model != "independent":
                raise ValueError(
                    "inclusion_probabilities requires joint_model='independent'."
                )
        if self.resolution not in {"none", "sample", "mode"}:
            raise ValueError("resolution must be one of: 'none', 'sample', or 'mode'.")
        if self.resolution == "sample" and self.seed is None:
            raise ValueError("resolution='sample' requires an explicit seed.")
        if isinstance(self.seed, bool) or (
            self.seed is not None and not isinstance(self.seed, int)
        ):
            raise TypeError("seed must be an integer or None.")
        if isinstance(self.tolerance, bool) or not isinstance(
            self.tolerance, (int, float)
        ):
            raise TypeError("tolerance must be a finite nonnegative number.")
        if not math.isfinite(self.tolerance) or self.tolerance < 0:
            raise ValueError("tolerance must be a finite nonnegative number.")

    @classmethod
    def from_value(
        cls, value: "ProbabilisticResponse | dict | None"
    ) -> "ProbabilisticResponse | None":
        if value is None or isinstance(value, cls):
            return value
        if isinstance(value, dict):
            return cls(**value)
        raise TypeError("probabilistic_response must be ProbabilisticResponse, dict, or None.")

    def to_dict(self) -> dict:
        data = {
            "representation": self.representation,
            "resolution": self.resolution,
            "seed": self.seed,
            "tolerance": self.tolerance,
        }
        if self.joint_model is not None:
            data["joint_model"] = self.joint_model
        return data

    def validate(self, probabilities: Sequence[float], option_count: int) -> list[float]:
        if isinstance(probabilities, (str, bytes)) or not isinstance(
            probabilities, (list, tuple)
        ):
            raise ValueError("probabilities must be a list with one value per option.")
        if len(probabilities) != option_count:
            raise ValueError(
                f"Expected {option_count} probabilities, got {len(probabilities)}."
            )

        validated: list[float] = []
        for index, value in enumerate(probabilities):
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise ValueError(f"Probability at index {index} must be numeric.")
            probability = float(value)
            if not math.isfinite(probability):
                raise ValueError(f"Probability at index {index} must be finite.")
            if probability < 0:
                raise ValueError(f"Probability at index {index} must be nonnegative.")
            validated.append(probability)

        if self.representation == "categorical":
            total = math.fsum(validated)
            if not math.isclose(total, 1.0, rel_tol=0.0, abs_tol=self.tolerance):
                raise ValueError(
                    f"Probabilities must sum to 1 within tolerance {self.tolerance}; "
                    f"got {total}."
                )
        else:
            for index, probability in enumerate(validated):
                if probability > 1:
                    raise ValueError(
                        f"Inclusion probability at index {index} must be at most 1."
                    )
        return validated

    def resolve(
        self,
        probabilities: Sequence[float],
        *,
        n: int = 1,
        seed: int | None = None,
        context: dict | None = None,
    ) -> list[dict]:
        """Resolve a validated categorical distribution without another model call."""
        if isinstance(n, bool) or not isinstance(n, int):
            raise TypeError("n must be an integer.")
        if n < 1:
            raise ValueError("n must be at least 1.")
        if isinstance(seed, bool) or (seed is not None and not isinstance(seed, int)):
            raise TypeError("seed must be an integer or None.")
        values = self.validate(probabilities, len(probabilities))
        base_seed = self.seed if seed is None else seed
        effective_seed = (
            self.derive_seed(base_seed, context)
            if base_seed is not None and context is not None
            else base_seed
        )

        if self.resolution == "none":
            return [
                {"index": None, "draw": None, "seed": effective_seed, "method": "none"}
                for _ in range(n)
            ]
        if self.representation == "inclusion_probabilities":
            if self.resolution == "mode":
                indices = [
                    index for index, probability in enumerate(values) if probability >= 0.5
                ]
                return [
                    {
                        "indices": indices,
                        "draw": None,
                        "seed": effective_seed,
                        "method": "mode",
                    }
                    for _ in range(n)
                ]
            if effective_seed is None:
                raise ValueError("Independent Bernoulli sampling requires an explicit seed.")
            rng = random.Random(effective_seed)
            resolutions = []
            for _ in range(n):
                draws = [rng.random() for _ in values]
                resolutions.append(
                    {
                        "indices": [
                            index
                            for index, (draw, probability) in enumerate(
                                zip(draws, values)
                            )
                            if draw < probability
                        ],
                        "draw": draws,
                        "seed": effective_seed,
                        "method": "sample",
                    }
                )
            return resolutions
        if self.resolution == "mode":
            index = max(range(len(values)), key=values.__getitem__)
            return [
                {"index": index, "draw": None, "seed": effective_seed, "method": "mode"}
                for _ in range(n)
            ]
        if effective_seed is None:
            raise ValueError("Categorical sampling requires an explicit seed.")

        rng = random.Random(effective_seed)
        resolutions = []
        for _ in range(n):
            draw = rng.random()
            cumulative = 0.0
            index = len(values) - 1
            for candidate, probability in enumerate(values):
                cumulative += probability
                if draw < cumulative:
                    index = candidate
                    break
            resolutions.append(
                {
                    "index": index,
                    "draw": draw,
                    "seed": effective_seed,
                    "method": "sample",
                }
            )
        return resolutions

    @staticmethod
    def derive_seed(base_seed: int, context: dict) -> int:
        """Derive a stable response-specific seed from canonical identifiers."""
        payload = json.dumps(
            {"base_seed": base_seed, "context": context},
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
            default=str,
        ).encode("utf-8")
        return int.from_bytes(hashlib.sha256(payload).digest()[:8], "big")

    @staticmethod
    def seed_context(
        *,
        agent: object,
        scenario: object,
        question_name: str,
        iteration: int,
    ) -> dict:
        """Build the canonical response identity shared by all execution engines."""

        def identity(value: object) -> object:
            if hasattr(value, "to_dict"):
                try:
                    value = value.to_dict(add_edsl_version=False)
                except TypeError:
                    value = value.to_dict()

            if isinstance(value, dict):
                return {
                    key: identity(item)
                    for key, item in value.items()
                    if key not in {"edsl_version", "edsl_class_name"}
                }
            if isinstance(value, (list, tuple)):
                return [identity(item) for item in value]
            return value

        agent_identity = identity(agent)
        scenario_identity = identity(scenario)
        return {
            "interview": {
                "agent": agent_identity,
                "scenario": scenario_identity,
                "iteration": iteration,
            },
            "agent": agent_identity,
            "scenario": scenario_identity,
            "question": question_name,
            "iteration": iteration,
        }
