"""Contracts and host-side resolution for probabilistic question responses."""

from __future__ import annotations

from dataclasses import dataclass
import math
import random
from typing import Literal, Sequence


ResolutionMethod = Literal["none", "sample", "mode"]


@dataclass(frozen=True)
class ProbabilisticResponse:
    """Configure probability elicitation and host-side answer resolution.

    The first supported representation is ``categorical``, used by multiple-choice
    questions.  Randomness is generated by EDSL after model response validation.
    """

    representation: Literal["categorical"] = "categorical"
    resolution: ResolutionMethod = "none"
    seed: int | None = None
    tolerance: float = 1e-6

    def __post_init__(self) -> None:
        if self.representation != "categorical":
            raise ValueError(
                "Multiple-choice probabilistic responses require "
                "representation='categorical'."
            )
        if self.resolution not in {"none", "sample", "mode"}:
            raise ValueError("resolution must be one of: 'none', 'sample', or 'mode'.")
        if self.resolution == "sample" and self.seed is None:
            raise ValueError("resolution='sample' requires an explicit seed.")
        if isinstance(self.seed, bool) or (
            self.seed is not None and not isinstance(self.seed, int)
        ):
            raise TypeError("seed must be an integer or None.")
        if not math.isfinite(self.tolerance) or self.tolerance < 0:
            raise ValueError("tolerance must be a finite nonnegative number.")

    @classmethod
    def from_value(
        cls, value: "ProbabilisticResponse | dict | None"
    ) -> "ProbabilisticResponse | None":
        if value is None or isinstance(value, cls):
            return value
        if isinstance(value, dict):
            return cls(**value)
        raise TypeError("probabilistic_response must be ProbabilisticResponse, dict, or None.")

    def to_dict(self) -> dict:
        return {
            "representation": self.representation,
            "resolution": self.resolution,
            "seed": self.seed,
            "tolerance": self.tolerance,
        }

    def validate(self, probabilities: Sequence[float], option_count: int) -> list[float]:
        if isinstance(probabilities, (str, bytes)) or not isinstance(
            probabilities, (list, tuple)
        ):
            raise ValueError("probabilities must be a list with one value per option.")
        if len(probabilities) != option_count:
            raise ValueError(
                f"Expected {option_count} probabilities, got {len(probabilities)}."
            )

        validated: list[float] = []
        for index, value in enumerate(probabilities):
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise ValueError(f"Probability at index {index} must be numeric.")
            probability = float(value)
            if not math.isfinite(probability):
                raise ValueError(f"Probability at index {index} must be finite.")
            if probability < 0:
                raise ValueError(f"Probability at index {index} must be nonnegative.")
            validated.append(probability)

        total = math.fsum(validated)
        if not math.isclose(total, 1.0, rel_tol=0.0, abs_tol=self.tolerance):
            raise ValueError(
                f"Probabilities must sum to 1 within tolerance {self.tolerance}; "
                f"got {total}."
            )
        return validated

    def resolve(
        self,
        probabilities: Sequence[float],
        *,
        n: int = 1,
        seed: int | None = None,
    ) -> list[dict]:
        """Resolve a validated categorical distribution without another model call."""
        if n < 1:
            raise ValueError("n must be at least 1.")
        values = self.validate(probabilities, len(probabilities))
        effective_seed = self.seed if seed is None else seed

        if self.resolution == "none":
            return [
                {"index": None, "draw": None, "seed": effective_seed, "method": "none"}
                for _ in range(n)
            ]
        if self.resolution == "mode":
            index = max(range(len(values)), key=values.__getitem__)
            return [
                {"index": index, "draw": None, "seed": effective_seed, "method": "mode"}
                for _ in range(n)
            ]
        if effective_seed is None:
            raise ValueError("Categorical sampling requires an explicit seed.")

        rng = random.Random(effective_seed)
        resolutions = []
        for _ in range(n):
            draw = rng.random()
            cumulative = 0.0
            index = len(values) - 1
            for candidate, probability in enumerate(values):
                cumulative += probability
                if draw < cumulative:
                    index = candidate
                    break
            resolutions.append(
                {
                    "index": index,
                    "draw": draw,
                    "seed": effective_seed,
                    "method": "sample",
                }
            )
        return resolutions
